name: Gomon CI/CD Pipeline

on:
  push:
    branches: ["main"]
    tags:
      - "v*"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"
          cache: true
          
      - name: Install CA certificates
        run: sudo apt-get update && sudo apt-get install -y ca-certificates
        
      - name: Build
        run: go build -v -o gomon ./cmd/gomon
        
      - name: Build for multiple platforms
        run: |
          mkdir -p dist
          GOOS=linux GOARCH=amd64 go build -o dist/gomon-linux-amd64 ./cmd/gomon
          GOOS=darwin GOARCH=amd64 go build -o dist/gomon-darwin-amd64 ./cmd/gomon
          GOOS=darwin GOARCH=arm64 go build -o dist/gomon-darwin-arm64 ./cmd/gomon
          GOOS=windows GOARCH=amd64 go build -o dist/gomon-windows-amd64.exe ./cmd/gomon
          
      - name: Archive production artifacts
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: gomon-binaries
          path: dist/
  
  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Download build artifacts
        uses: actions/download-artifact@v4  # Updated from v3 to v4
        with:
          name: gomon-binaries
          path: dist
          
      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/gomon-linux-amd64
            dist/gomon-darwin-amd64
            dist/gomon-darwin-arm64
            dist/gomon-windows-amd64.exe
          draft: false
          prerelease: false
          generate_release_notes: true
